version: '3'
networks:
  monitor:
    driver: bridge
services:
  prometheus:
    build: ./prometheus/soft/prometheus-dockerfile/
    container_name: prometheus
    hostname: prometheus
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus/rules:/prometheus/rules
      - ./prometheus/data/:/prometheus/data/
      - ./prometheus/sd_config/:/prometheus/sd_config/
    ports:
      - "9090:9090"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - ./grafana:/var/lib/grafana/
    ports:
      - "3000:3000"
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - "9093:9093"
      - "9094:9094"
    networks:
      - monitor

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    hostname: pushgateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9091:9091"
    networks:
      - monitor

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.21.1
    container_name: blackbox-exporter
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9115:9115"
    networks:
      - monitor

